language: java
script:
  -mvn install
  -mvn compile
before_install:
  -git clone git@github.com:samutamm/PaivanUutiset.git
  -cd PaivanUutiset
  -mvn install
  -cd ..
  -git clone git@github.com:samutamm/HackerNewsUutiset.git
  -cd HackerNewsUutiset
  -mvn install
  -cd ..
