language: java
script:
  - mvn install
  - mvn compile
before_install:
  - git clone https://github.com/samutamm/PaivanUutiset.git
  - cd PaivanUutiset
  - mvn install
  - cd ..
  - git clone https://github.com/samutamm/HackerNewsUutiset.git
  - cd HackerNewsUutiset
  - mvn install
  - cd ..
